# This message contains a list of motion planning constraints.

# Joint constraint
tmc_manipulation_msgs/JointConstraint[] joint_constraints
# Frame's position constraint
tmc_manipulation_msgs/PositionConstraint[] position_constraints
# Frame's orientation constraint
tmc_manipulation_msgs/OrientationConstraint[] orientation_constraints
# Visibility constraint
tmc_manipulation_msgs/VisibilityConstraint[] visibility_constraints
